version: '3'
services:
  indy-pool:
    # following build code required if we mmaking any changes in Code then it will rebuild that image
    #build:
    #  context: .
    #  dockerfile: docker/indy-pool.dockerfile
    # following image is only for first time before tagging with registry server for local environment setup,after that once u tag image proprly will not need this
    #image: indy-pool
    image: mysampleappacrdocker.azurecr.io/indy-pool:v1
    container_name: indy-pool
    ports:
      - "9701-9709:9701-9709"

  web-agent-1:
    #build:
    #  context: .
    #  dockerfile: docker/web-agent.dockerfile
    image: mysampleappacrdocker.azurecr.io/web-agent-1:v1
    container_name: web-agent-1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOCKER_HOST=http://20.237.84.81:80  #need to hcange this ip whenver you will host in new node, or you can set this in env file
      - ASPNETCORE_URLS=http://host.docker.internal:80  #if docker host code is not given this url will be used  - check startup file in code for mroe detials we using these variable
    ports:
      - "80:80"
    depends_on:
      - "indy-pool"
    links:
      - "indy-pool"

