apiVersion: v1
kind: Service
metadata:
    name: "blockchainpocaks-34f7"
    labels:
        app: "blockchainpocaks-34f7"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "blockchainpocaks-34f7"